// src/app/layout.tsx
import type { Metadata } from "next";
// --- FIX: Use a standard Google Font like Inter ---
import { Inter, Roboto_Mono } from "next/font/google"; // <--- CORRECT IMPORT

import "./globals.css";

const inter = Inter({ // <--- CORRECT FUNCTION CALL
  variable: "--font-sans",
  subsets: ["latin"],
});

const robotoMono = Roboto_Mono({ // <--- CORRECT FUNCTION CALL
  variable: "--font-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        // --- FIX: Use the new font variables ---
        className={`${inter.variable} ${robotoMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}